name: Lint and Format

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your desired Python version

      - name: Install dependencies
        run: pip install flake8 black

      - name: Run Flake8
        run: |
          flake8 || true  # Ignore exit code and continue

      - name: Run Black
        run: black .

      - name: Fetch source branch
        run: |
          SOURCE_BRANCH=${{ github.head_ref }}
          git fetch origin $SOURCE_BRANCH:$SOURCE_BRANCH

      - name: Checkout source branch
        run: |
          git checkout $SOURCE_BRANCH

      - name: Commit formatted code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format code using Black"
          git push origin $SOURCE_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
