name: Lint and Format

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_PERSONAL_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install flake8 and black
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run flake8 and capture output
      run: |
        flake8 . > flake8_output.txt 2>&1
        if [ $? -ne 0 ]; then
          echo "Flake8 found issues:"
          cat flake8_output.txt
          exit 1
        fi

    - name: Format code with black
      run: black .

    - name: Commit and push changes (including Flake8 output)
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'githubaction@git.com'
        git commit -am "Format Python code with black" || echo "No changes to commit"
        git push origin HEAD:${{ github.head_ref }}
        git checkout ${{ github.head_ref }}
        git add flake8_output.txt
        git commit -m "Add Flake8 output"
        git push origin HEAD:${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
