name: Django CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v2
    - run: pip install black
    - run: black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v2
    - run: pip install isort
    - run: isort --recursive --check-only --diff

  flake8:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/setup-python@v1
     - uses: actions/checkout@v2
     - run: pip install flake8
     - run: flake8 --ignore E501,E231,W503
